# One CLI to format the code tree - https://github.com/numtide/treefmt

# Do not exit with error if a configured formatter is missing
# Env $TREEFMT_ALLOW_MISSING_FORMATTER
# allow-missing-formatter = true

# The file into which a cpu profile will be written
# Env $TREEFMT_CPU_PROFILE
# cpu-profile = ./cpu.pprof

# Exclude files or directories matching the specified globs
# Env $TREEFMT_EXCLUDES
# excludes = ["*.md", "*.gif"]

# Exit with error if any changes were made during execution
# Useful for CI
fail-on-change = true

# A list of formatters to apply
# Defaults to all configured formatters
# Env $TREEFMT_FORMATTERS
# formatters = ["gofmt", "prettier"]

# Log paths that did not match any formatters at the specified log level
on-unmatched = "warn"

# The root directory from which treefmt will start walking the filesystem
# Defaults to the directory containing the config file
# Env $TREEFMT_TREE_ROOT
# tree-root = "/tmp/foo"

# File to search for to find the tree root (if tree-root is not set)
# Env $TREEFMT_TREE_ROOT_FILE
# tree-root-file = ".git/config"

# Set the verbosity of logs
verbose = 1

# The method used to traverse the files within the tree root
# Use git to only format tracked files
walk = "git"

# [formatter.mylanguage]
# # Command to execute
# command = "command-to-run"
# # Command-line arguments for the command
# options = []
# # Glob pattern of files to include
# includes = [ "*.<language-extension>" ]
# # Glob patterns of files to exclude
# excludes = []
# # Controls the order of application when multiple formatters match the same file
# # Lower the number, the higher the precedence
# # Default is 0
# priority = 0

[formatter.deadnix]
command = "deadnix"
includes = ["*.nix"]
priority = 0

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]
priority = 1

[formatter.github-actions]
command = "actionlint"
includes = [".github/workflows/*.yml"]
priority = 2

[formatter.bash]
command = "beautysh"
includes = ["*.sh", ".envrc"]
priority = 3

[formatter.javascript]
command = "biome"
options = ["format", "--write"]
includes = ["*.{js,jsx,ts,tsx,json}"]
priority = 4

[formatter.yaml]
command = "yamlfmt"
includes = ["*.{yml,yaml}"]
priority = 5

[formatter.toml]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
priority = 6

[formatter.rust]
command = "rustfmt"
options = ["--edition", "2024"]
includes = ["*.rs"]
priority = 7
